name: intronmodel
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - matplotlib
  - ipympl
  - biopython
  - pytorch
  - cuda-cudart-dev
  - cuda-nvcc-tools
  - transformers
  - einops
  - huggingface_hub
  - scikit-learn
  - setproctitle
  - tqdm
  - pyyaml
  - xgboost
  - gffcompare
  - pip:
      - pytest>=8.0
      - sphinx>=8.0
      - myst-parser>=4.0
      - reservoir-computing>=1.0.2
